### ISSUE TITLE
About user-sketched density

### ISSUE THREAD

**Issue by xchhuang** [jgain/EcoLearn#2]
Hi,

Thanks for your great work. I am interested in user-sketched density, it is mentioned in the paper that they are created by hand. Is there a standalone interface to do so given the canopy footprint?  Thanks in advance.

**Comment by eric-guerin** [comment]
Dear Xingchang,
Thanks for your interest in our work. We did not have any particular interface for the drawing of the user-sketched density maps from the canopy footprint. I have used an iPad with a pencil and Adobe Sketchbook app. Using layers allowed me to see simultaneously the canopy footprint (CFP) and the painted density (CD). Note that we could also try to infer the CD from CFP using a few examples using another pix2pix. Because the process is simple, it should work with a limited number of examples.

**Comment by xchhuang** [comment]
Dear Eric,

Thanks for your additional information, that's helpful!
